#!/usr/bin/env bash
#=
# config
##   Functions related to setting up configuation
    #- chshell
    #- shelltheme
    #- vimrc
    #- vim plugins
    #- bashrc
    #- gitconfig
    #- aws
    #- ssh
    #- private keys
    #- dotfiles
#=


function install_ssh {
  cd $HOME
  mkdir .ssh
  cd .ssh
  ssh-keygen
  # aws s3 ls s3://iangolden/authorized_keys
  ssh-agent add
}

# Install AWS
function install_awscli {
  pip3 install awscli --upgrade --user
}

# Configure AWS
function configure_awscli {
  # TODO -- conditional here to optionally configure later
  #   - answer=read "Continue? y/n"
  # TODO -- put setup credentials in S3
  aws configure
}

function install_dotfiles {

}

function install_aws {
  install_awscli
  configure_awscli
}


